name: knd775
favicon: null
layout_spectrum: 0.18820979981683195
typography_spectrum: 0.6972771780565381
title: Ben Ayles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#390599'
    - '#4000aa'
    - '#0000ff'
    - '#5500aa'
    - '#2b00aa'
  brandStrength: 1
  lightness: 0.32430941238999367
  saturation: 0.35532176797278225
  rhythmicContrast: 0.5326487610582262
purpose: []
