name: knd775
favicon: null
layout_spectrum: 0.00794
typography_spectrum: 0.24603
title: Ben Ayles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#390599'
    - '#4000aa'
    - '#0000ff'
    - '#5500aa'
    - '#2b00aa'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
